"""Provenance metadata. No sample leaves any stage without it.

Every emitted sample carries {source, license, extraction_method, repo_sha}.
For external corpora the license is read from the live HF card at download
time (stage 5) and hard-fails on mismatch — never hardcoded and trusted.
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass, asdict
from functools import lru_cache
from pathlib import Path

from pipeline.config import LUMAKIT_REPO, GROK_REPO, LUMABOT_REPO


@lru_cache(maxsize=16)
def git_sha(repo: Path) -> str:
    """Full HEAD SHA of a source repo, or 'unknown' if not a git checkout."""
    try:
        out = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=str(repo),
            capture_output=True,
            text=True,
            check=True,
        )
        return out.stdout.strip()
    except Exception:
        return "unknown"


@dataclass(frozen=True)
class Provenance:
    source: str            # e.g. "LumaKit" / "grok-build-fork" / HF dataset id
    license: str           # SPDX-ish identifier, verified at extraction time
    extraction_method: str # which extractor + which technique
    repo_sha: str          # source commit, or dataset revision for HF sets

    def to_dict(self) -> dict:
        return asdict(self)


# --------------------------------------------------------------------------
# Known first-party sources. License strings are asserted against the actual
# LICENSE file on disk by verify_source_licenses().
# --------------------------------------------------------------------------

SOURCE_LICENSES = {
    "LumaKit": "MIT",
    "grok-build-fork": "Apache-2.0",
    # Resolved 2026-08-11: LumaBot originally shipped with no LICENSE file,
    # which defaults to all rights reserved. MIT added upstream in 7e11fa0,
    # matching LumaKit's licence and copyright holder.
    "LumaBot": "MIT",
}

# Sources known to lack a verifiable licence grant. Empty is the good state;
# the machinery stays so a future source can be flagged rather than assumed.
UNLICENSED_SOURCES: set[str] = set()


def lumakit(extraction_method: str) -> Provenance:
    return Provenance(
        source="LumaKit",
        license=SOURCE_LICENSES["LumaKit"],
        extraction_method=extraction_method,
        repo_sha=git_sha(LUMAKIT_REPO),
    )


def grok(extraction_method: str) -> Provenance:
    return Provenance(
        source="grok-build-fork",
        license=SOURCE_LICENSES["grok-build-fork"],
        extraction_method=extraction_method,
        repo_sha=git_sha(GROK_REPO),
    )


def lumabot(extraction_method: str) -> Provenance:
    """LumaBot provenance. See SOURCE_LICENSES for the licensing caveat."""
    return Provenance(
        source="LumaBot",
        license=SOURCE_LICENSES["LumaBot"],
        extraction_method=extraction_method,
        repo_sha=git_sha(LUMABOT_REPO),
    )


def unresolved_licenses() -> list[str]:
    """Sources whose licence is not a verifiable permissive grant.

    Surfaced by `pipeline.doctor` and reproduced in MIXTURE.md rather than
    quietly normalised to something that looks compliant.
    """
    out = []
    for name in sorted(UNLICENSED_SOURCES):
        repo = {"LumaBot": LUMABOT_REPO}.get(name)
        if repo is None or not repo.exists():
            continue
        has_license = any(
            (repo / f).exists()
            for f in ("LICENSE", "LICENSE.md", "LICENSE.txt", "COPYING")
        )
        if not has_license:
            out.append(name)
    return out


def synthetic(extraction_method: str, teacher_model: str) -> Provenance:
    """Trajectories are generated by a teacher against LumaKit's own runtime.

    The generated text is a derivative of a permissively licensed harness plus
    an Apache-2.0 model's outputs; we record both so MIXTURE.md can justify it.
    """
    return Provenance(
        source=f"synthetic:LumaKit-trajectories:{teacher_model}",
        license="MIT AND Apache-2.0",
        extraction_method=extraction_method,
        repo_sha=git_sha(LUMAKIT_REPO),
    )


class LicenseMismatch(RuntimeError):
    """Raised when a source's actual license does not match what we recorded."""


def verify_source_licenses() -> None:
    """Hard-fail if a source repo's LICENSE no longer matches expectations.

    Cheap insurance: this dataset is being built for commercial compliance, so
    a silently relicensed source must stop the pipeline, not warn.
    """
    checks = [
        (LUMAKIT_REPO, "MIT", "MIT License"),
        (GROK_REPO, "Apache-2.0", "Apache License"),
        (LUMABOT_REPO, "MIT", "MIT License"),
    ]
    for repo, spdx, needle in checks:
        path = repo / "LICENSE"
        if not path.exists():
            raise LicenseMismatch(f"{repo.name}: LICENSE file missing")
        head = path.read_text(encoding="utf-8", errors="replace")[:400]
        if needle not in head:
            raise LicenseMismatch(
                f"{repo.name}: expected {spdx} (looked for {needle!r}), "
                f"got: {head.splitlines()[0] if head else '<empty>'!r}"
            )
